acadamics = {
    ' AP' : 'https://drive.google.com/drive/folders/1Ft6zrVTEXD2f6WAYcZDUIW1SUaqAf8ci',
    ' AP lab' : 'https://drive.google.com/drive/folders/1FUKTC_6jRArlrl5l2guXgFbDXmjKc6Wz',
    ' BIOT' : 'https://drive.google.com/drive/folders/1FgEJQ0R6Wq5Bg3DNuOajrJVjJezeChbY',
    ' CP Lab' : 'https://drive.google.com/drive/folders/1Fg8-p5pALM39kEjsQaApkezkbV9j8mq8',
    ' Ds Lab' : 'https://drive.google.com/drive/folders/1kB6E8_CpLquKauNf6yMrtf2mgaTFxjzn',
    ' EC' : 'https://drive.google.com/drive/folders/1mpfIur1xilci72LHtV4Ue7XicKsHLkV0',
    ' ED' : 'https://drive.google.com/drive/folders/1Fiw0WaktCX4BMWg1xShhSXo-mrdh4XyN',
    ' ENGLISH' : 'https://drive.google.com/drive/folders/1-vExxFF-iQ-fIz3hj0aUIj6Le-5tyyzg',
    ' LAC' : 'https://drive.google.com/drive/folders/1G2aevbgMrEwXqraU9_E0LLLO9f00laad',
    ' ODE' : 'https://drive.google.com/drive/folders/16bNx_eQDCK_G8MmBUDNzX-IgA2YJlMcZ',
    ' PPS' : 'https://drive.google.com/drive/folders/1FkHiKgebxiDDVoWwIE6gY3DEuLanOP2W',
    ' BEE' : 'https://drive.google.com/drive/folders/1gLqVZosBBL-h4Z-SncKMvzi3Miqr2zbh',
    ' COA' :  'https://drive.google.com/drive/folders/1iAehtWI58n084zWyqEBTZtubqa4dw9oc',
    ' DAA' : 'https://drive.google.com/drive/folders/17CP7r9BMAWz6YjvNFf_Xbq9eVq23DDt4',
    ' DBMS' : 'https://drive.google.com/drive/folders/1KWsu2asfYez38HeDc4nSTBO8RXbBTjmo',
    ' ML' : 'https://drive.google.com/drive/folders/1t0ICCfmeCFxY7KMeat8IXieklK5ROZp7',
    ' JAVA LAB' : 'https://drive.google.com/drive/folders/11crsJlKZ6VDqoyrgrRifl3g0Rjg5m4eS',
    ' NTPD' : 'https://drive.google.com/drive/folders/1t088UDpNsZul7F3gqythKGUgpPQGOAMR',
    ' OOP' : 'https://drive.google.com/drive/folders/1bkg9JmqHESnsuUiDCvf4iwuSex2coKzD',
    ' OS' : 'https://drive.google.com/drive/folders/1OmXQGRySDWDCUZ07Ky3n2f_RD4RqCcdo',
    ' OS LAB' : 'https://drive.google.com/drive/folders/1m-7HtZQAw00rhIKTlnf3gUH0m_BEawlc',
    ' CV' : 'https://drive.google.com/drive/folders/1ZKd0-rjAnCKGAfSyxyPcYHxIis69n3Ta',
    ' CN' : 'https://drive.google.com/drive/folders/1L9DARmhwqPeDW0w364gIHBvc94wo1xjI',
    ' APP' : 'https://drive.google.com/drive/folders/1abyxREKnplsmm9EJyIcvHw_k82H_vV-U',
    ' TOC' : 'https://drive.google.com/drive/folders/1a0jiBqUSYnisAR8WFTTF0AtEAienD3v7',
    ' AI' : 'https://drive.google.com/drive/folders/1T56-hk92hzyKiONVz9Lfg8s6WtJypIly',
}